# Yield
- When you are on the road you may come across "yield to pedestrians" sign boards which require you to stop and give way to pedestrians crossing the road. 
- Python's use of the word yield can both produce values and also give way.

```python
def keep_learning_asynchronous():
    yield "Educative"


if __name__ == "__main__":
    str = keep_learning_asynchronous()
    str = next(gen)
    print(str)
```

What is happening ☝️?

❗So instead of being returned the string, we are returned a generator object as the print statement shows. In fact our method **keep_learning_asynchronous() is now a generator function**. Generator functions are called as generators because they generate values.
**Since we are passing generator objects into next() we can conclude that generators are iterators.**
We can use for loops with a generator also:

```python
gen = keep_learning_asynchronous()
    for item in gen:
        print(item)
```

### Multiple yield statements 
```python
def keep_learning_asynchronous():
    yield "Educative"
    yield "is great!"


if __name__ == "__main__":
    gen = keep_learning_asynchronous()
    for item in gen:
        print(item)
```

### Return and Yield together , how to capture StopIteration exception 
👉 If we attempt to invoke next() on a generator object that had already produced (yielded) all its values, we'll be thrown a **StopIteration** exception.

```python 
def keep_learning_asynchronous():
    yield "Educative"
    return "is great"


if __name__ == "__main__":
    gen = keep_learning_asynchronous()

    first_string = next(gen)
    print(first_string)

    try:
        next(gen)
    except StopIteration as e:
        second_string = e.value
        print(second_string) 
```
👉 Also **Anytime you return from a generator function, it'll be equivalent of raising the StopIteration exception.**

### Suspended State 
>Yield allows a function to return a value and let the state of the function suspend till next() is invoked on the associated generator object.

# Generators
✔ Using a yield expression in a function’s body causes that function to be a generator. 

✔ These functions return an object which supports the iteration protocol methods. The generator object created, automatically receives a __next()__ method. 

✔ Generator functions allow us to procrastinate computing expensive values. We only compute the next value when required. This makes generators memory and compute efficient. They refrain from saving long sequences in memory or doing all expensive computations upfront.

✔ Generators when suspended retain the code location, which is the last yield statement executed, and their entire local scope. This allows them to resume execution from where they left off.

✔ Generator objects are nothing more than iterators.

### States of a generator
A generator goes through the following states:

1. **GEN_CREATED** when a generator object has been returned for the first time from a generator function and iteration hasn't started.

2. **GEN_RUNNING** when next has been invoked on the generator object and is being executed by the python interpreter.

3. **GEN_SUSPENDED** when a generator is suspended at a yield

4. **GEN_CLOSED** when a generator has completed execution or has been closed. We'll learn about closing generators later.

### Methods of Generator Objects
A generator object exposes different methods that can be invoked to manipulate the generator. These are:

    ✔throw()

    ✔send()

    ✔close()

#### Close() Method

- The intent of the close() method is to give the generator a chance to clean-up before it exits.
- A generator function can catch the GeneratorException and perform clean-up actions.

What happens in the code below 👇

```python
def get_item():
    try:
        yield 5

    except GeneratorExit:
        print("GeneratorExit exception raised")


if __name__ == "__main__":
    gen = get_item()

    print(next(gen))
    print("Main exiting")
```

>Notice the exception raised statement appears in the output after the main exiting statement. The Python interpreter garbage collects the gen variable, which is a generator, and invokes close() on it, which is why the exception raised statement is printed after the main exiting statement.

👉Contrast the above output with the one below, where we explicitly invoke the close() method on the gen object

```python 
def get_item():
    try:
        yield 5

    except GeneratorExit:
        print("GeneratorExit exception raised")


if __name__ == "__main__":
    gen = get_item()

    print(next(gen))
    gen.close()
    print("main exiting")
```

#### Send() in Generator 

- we can also pass data to a generator function using the send() method defined on the associated generator object
- Passing a value to generator can be done in two ways 

👉Way1
```python 
def generator_function():
    while True:
        item = yield
        print("received " + str(item))


if __name__ == "__main__":
    gen = generator_function()
    next(gen)
    gen.send(37)
```
👉Way2
```python
def generator_function():
    while True:
        item = yield
        print("received " + str(item))


if __name__ == "__main__":
    gen = generator_function()
    gen.send(None)
    gen.send(37)

```
>Note that before executing send() on the generator object we invoke next() in way1. The reason is that when the generator is starting out, there is no yield assignment statement that the generator is waiting on to receive a value

### Sending & Receiving
👉 ***Important***
```python
def generate_numbers():
    i = 0
    while True:
        i += 1
        yield i
        k = yield
        print(k)


if __name__ == "__main__":
    generator = generate_numbers()

    item = next(generator)
    print(item)

    # Nothing is received by the generator function   
    generator.send(5)
```
**output**: 1
>Note that in the above code the generator doesn't receive 5 when we send() it. The value 5 is lost as the generator isn't suspended at a yield assignment statement. In fact, the generator resumes execution from the first yield statement and immediately blocks at the second yield statement. In between, the two yield statements no other line of code is executed. The main method which invokes send() on the generator object receives None because **by definition send() returns the next yielded value in a generator function which is None.**

👉 To solve the above:
```python
def generate_numbers():
    i = 0
    while True:
        i += 1
        yield i
        k = yield
        print("Received in generator function: " + str(k))


if __name__ == "__main__":
    generator = generate_numbers()

    item = next(generator)
    print("Received in main script: " + str(item))

    # Nothing is received by the generator function   
    item = generator.send(None)
    print("Received in main script: " + str(item))

    # The second send is successful
    item = generator.send(5)
    print("Received in main script: " + str(item))
```

